markdown: redcarpet
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
company_name: "Siyelo"
title: "Siyelo DNA"
description: "The inner workings of a rather different consulting company"
